config/routes.rb
Rails.application.routes.draw do
 

 
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/trans'
  get 'sessions/new'
  get 'patient' => 'patients#new'
  get 'users/new'
  get 'patients/new'
  get    'signup'  => 'users#new'
  get    'patients'  => 'patients#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'trans'   => 'static_pages#trans'
  resources :users
  resources :patients
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
	

  protected
  def authenticate_user!
    if logged_in?
      super
    else
      redirect_to login_path
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
   @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new(patient_params)
  end
  def create
    params.permit!
   @patient = Patient.new(params[:patient])
      # Handle a successful save.
    if @patient.save
        flash[:success] = "Patient had been Added"
        redirect_to trans_path
    else
      render 'new'
    end
  end
   private

    def patient_params
      params.require(:patient).permit(:fname, :lname, :MRN, :SSN,
                                      :birthday) if params[:patient]
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

 def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to trans_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 
  def home
  end


  def trans
    if session[:user_id] == nil
     redirect_to login_path
    end
  end
  
  def trans
    @users = User.find(session[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(user_params)
  end
  def create
    params.permit!
    @user = User.new(params[:user])
      # Handle a successful save.
    if @user.save
        log_in @user
        flash[:success] = "Welcome the Dietary Crew!"
        redirect_to trans_path
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to trans_path
    else
      render 'edit'
    end
  end
  
   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation) if params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Hospital Meals"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
  
  
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
       session[:user_id] = user.id
    end
     # Returns the current logged-in user (if any).
    def current_user
       @current_user ||= User.find_by(id: session[:user_id])
    end
      # Returns true if the user is logged in, false otherwise.
    def logged_in?
       current_user != nil
    end
    def log_out
       session.delete(:user_id)
       @current_user = nil
    end
end

app/views/layouts/_Postheader.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Hospital Meals", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Hospital Meals Application</a>
    by <a href="https://www.facebook.com/daniel.salinas.984">Daniel Salinas</a>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Hospital Meals", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <% if logged_in? %>
        <li><%= link_to "MyPage",    trans_path %></li>
          <li><%= link_to "Ordering", '#' %></li>
          <li><%= link_to "Patients", patients_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<!--
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

-->
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Hospital Meals</h1>

  <h2>
    This is the home page for the Hospital Meals application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/trans.html.erb
<!--
<h1>StaticPages#trans</h1>
<p>Find me in app/views/static_pages/trans.html.erb</p>
-->

<% provide(:title, "trans") %>
<div>
   <h4>
      Welcome, <%= @users.name %>!
  </h4>
  <br>
  <h5>
  Click on the an icon below to continue:
  </h5>
    <div class = "jumbotron other-color">
        <div class="center">
            <table class="center" style="width:100%">
                <tr>
                    <td>Patient Management: </td>
                    <td colspan=2></td>
                    <td colspan=2>Ordering System:</td>
                </tr>
                <tr>
                    <td>
                        <%=link_to image_tag( "Records.png", :size=> "125x135"), patient_path %>
                    </td>
                    <td colspan=2></td>
                    <td colspan=2>
                        <%=link_to image_tag( "Order Image.png", :size=> "125x135"), login_path %>
                    </td>
                </tr>
                <tr>
                    <td>Menu Status: </td>
                    <td colspan=2></td>
                    <td>User Settings:</td>
                </tr>
                <tr>
                    <td>
                        <%=link_to image_tag( "cafeteria_icon.png", class: "myImage", :size=> "125x135"), "#" %>
                    </td>
                    <td colspan=2></td>
                    <td colspan=2>
                        <%=link_to image_tag( "gear_tools.png", :size=> "125x135"), edit_user_path(current_user) %>
                    </td </tr>
            </table>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!--
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
-->
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>